[project]
name = "videographer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "norfair>=2.2.0",
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
]
